CREATE table pages 
(
    page_id serial PRIMARY KEY, 
    name text,
    url text UNIQUE,
    content text
);

INSERT INTO pages (name, url, content)
    VALUES
    ('Main Page of the site', 'index', '<p>Wellcome to our site. We are the best.</p>'),
    ('About Page', 'about', '<div class="row mb-3"><p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architectodolore laudantiumullam, neque, quas iste eum enim, nihil vitae molestiae quisquam minus iure evenietet ratione porro corrupti quis asperiores.</p><img class="img-fluid mb-3" src="/media/img/our_company.webp" alt="Our company in Kyiv"><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet tenetur temporibusenim laborum possimus, soluta tempore praesentium, reprehenderit, nulla voluptatummagnam facilis distinctio repudiandae sit ullam. Placeat nulla quasi saepe?</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet tenetur temporibusenim laborum possimus, soluta tempore praesentium, reprehenderit, nulla voluptatummagnam facilis distinctio repudiandae sit ullam. Placeat nulla quasi saepe? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure maiores facilis at enim. Numquam, architecto? Doloribus molestias, laudantium, odio adipisci nulla odit, nemo error eius esse accusantium ullam numquam culpa?</p></div><div class="row justify-content-center"><div class="col-sm-3"><div class="card"><img class="card-img-top" src="/media/img/our_people.webp" alt="Our people"><div class="card-header bg-secondary text-white"><h5 class="card-title text-center ">Head mananger</h5></div><div class="card-body"><p class="card-text">Petro Sagaydachni</p><p class="card-text">Over 20 years of experience in the field of sellingcellular communication devices and implementing new communicationsystems in large companies worldwide</p></div></div></div><div class="col-sm-3"><div class="card"><img class="card-img-top" src="/media/img/our_people_2.webp" alt="Our people"><div class="card-header bg-secondary text-white"><h5 class="card-title text-center ">Chief Financial Officer</h5></div><div class="card-body"><p class="card-text">Olha Denna</p><p class="card-text">With extensive experience in finance, excellentknowledge of modern tools for financial analysis and decision-making,and a background in strategic financial planning accumulated over 15 years</p></div></div></div><div class="col-sm-3"><div class="card"><img class="card-img-top" src="/media/img/our_people_owner.jpg" alt="Our people"><div class="card-header bg-secondary text-white"><h5 class="card-title text-center ">Company owner</h5></div><div class="card-body"><p class="card-text">Andrii Mazepa</p><p class="card-text mb-0">Head of the association of enterprises and organizations of the country. </p><p class="card-text">Successful businessman and professor specializing in financial risks at Economic University.</p></div></div></div></div>')
;

-- HELPER
SELECT * FROM pages;

UPDATE pages SET content = '<div class="row mb-3">
<p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architectodolore laudantiumullam, neque, quas iste eum enim, nihil vitae molestiae quisquam minus iure evenietet ratione porro corrupti quis asperiores.</p><img class="img-fluid mb-3" src="/media/img/our_company.webp" alt="Our company in Kyiv"><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet tenetur temporibusenim laborum possimus, soluta tempore praesentium, reprehenderit, nulla voluptatummagnam facilis distinctio repudiandae sit ullam. Placeat nulla quasi saepe?</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet tenetur temporibusenim laborum possimus, soluta tempore praesentium, reprehenderit, nulla voluptatummagnam facilis distinctio repudiandae sit ullam. Placeat nulla quasi saepe? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure maiores facilis at enim. Numquam, architecto? Doloribus molestias, laudantium, odio adipisci nulla odit, nemo error eius esse accusantium ullam numquam culpa?</p></div><div class="row justify-content-center"><div class="col-sm-3"><div class="card"><img class="card-img-top" src="/media/img/our_people.webp" alt="Our people"><div class="card-header bg-secondary text-white"><h5 class="card-title text-center ">Head mananger</h5></div><div class="card-body"><p class="card-text">Petro Sagaydachni</p><p class="card-text">Over 20 years of experience in the field of sellingcellular communication devices and implementing new communicationsystems in large companies worldwide</p></div></div></div><div class="col-sm-3"><div class="card"><img class="card-img-top" src="/media/img/our_people_2.webp" alt="Our people"><div class="card-header bg-secondary text-white"><h5 class="card-title text-center ">Chief Financial Officer</h5></div><div class="card-body"><p class="card-text">Olha Denna</p><p class="card-text">With extensive experience in finance, excellentknowledge of modern tools for financial analysis and decision-making,and a background in strategic financial planning accumulated over 15 years</p></div></div></div><div class="col-sm-3"><div class="card"><img class="card-img-top" src="/media/img/our_people_owner.jpg" alt="Our people"><div class="card-header bg-secondary text-white"><h5 class="card-title text-center ">Company owner</h5></div><div class="card-body"><p class="card-text">Andrii Mazepa</p><p class="card-text mb-0">Head of the association of enterprises and organizations of the country. </p><p class="card-text">Successful businessman and professor specializing in financial risks at Economic University.</p></div></div></div></div>'
    WHERE name = 'About Page'
;

UPDATE pages SET content = $$<p class="lead">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam animi sint provident molestiae voluptate tenetur quae at porro fugit quidem! Repellat culpa qu is inventore placeat in illum numquam vitae adipisci? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis reiciendis aperiam, deserunt vel nisi voluptatib us illum exercitationem, expedita, assumenda unde autem in ab quos. Expedita porro alias earum nihil quidem!</p>
<p>Lorem ipsum dolor, <a href="#">sit amet consectetur</a> adipisicing elit. Nam animi sint provident molestiae voluptate tenetur quae at porro fugit quidem! Repellat culpa quis inventore placeat in illum numquam vitae adipisci?</p>
<div class="row my-3">
    <div class="col-sm-6">
        <img class="img-thumbnail" src="http://picsum.photos/500/500" alt="Some picture">
    </div>
    <div class="col-sm-6">
        <h2>Lorem ipsum dolor sit</h2>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem nostrum voluptatibus velit maxime perspiciatis nihil facilis tempora ullam enim repudiandae! Nihil laborum eaque doloremque facere obcaecati? Ipsam, praesentium quas. Quod? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure delectus error molestias debitis corrupti fugiat eos repellendus, nostrum, incidunt repudiandae pariatur illo, cupiditate tenetur modi. Voluptatem molestias expedita nisi iure.</p>
        <button class="btn btn-secondary my-3" type="button">Details</button>
    </div>
</div>$$
    WHERE name = 'Main Page of the site'
;

--<p class="lead">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam animi sint provident molestiae voluptate tenetur quae at porro fugit quidem! Repellat culpa quis inventore placeat in illum numquam vitae adipisci? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis reiciendis aperiam, deserunt vel nisi voluptatibus illum exercitationem, expedita, assumenda unde autem in ab quos. Expedita porro alias earum nihil quidem!</p><p>Lorem ipsum dolor, <a href="#">sit amet consectetur</a> adipisicing elit. Nam animi sint provident molestiae voluptate tenetur quae at porro fugit quidem! Repellat culpa quis inventore placeat in illum numquam vitae adipisci?</p><div class="row my-3"><div class="col-sm-6"><img class="img-thumbnail" src="http://picsum.photos/500/500" alt="Some picture"></div><div class="col-sm-6"><h2>Lorem ipsum dolor sit</h2><p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem nostrum voluptatibus velit maxime perspiciatis nihil facilis tempora ullam enim repudiandae! Nihil laborum eaque doloremque facere obcaecati? Ipsam, praesentium quas. Quod? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure delectus error molestias debitis corrupti fugiat eos repellendus, nostrum, incidunt repudiandae pariatur illo, cupiditate tenetur modi. Voluptatem molestias expedita nisi iure.</p><button class="btn btn-secondary my-3" type="button">Details</button></div></div>